title: "Dragon — Portfolio"
description: "Professional portfolio of Dragon (dragonsenseiguy) — Python, Data Science, Web Development."
url: "https://dragonsenseiguy.github.io"
author: "Dragon"
github_username: "dragonsenseiguy"
# Use plain static HTML/CSS without a Jekyll theme
theme: null
plugins: []
# Keep README out of the built site
exclude:
  - README.md

